const actionTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    TOGGLE_TROLLEY_HIDDEN: "TOGGLE_TROLLEY_HIDDEN",
    ADD_ITEM_TO_TROLLEY: "ADD_ITEM_TO_TROLLEY",
    REMOVE_SINGLE_ITEM_FROM_TROLLEY: "REMOVE_SINGLE_ITEM_FROM_TROLLEY",
    REMOVE_ALL_ITEM_INSTANCES_FROM_TROLLEY: "REMOVE_ALL_ITEM_INSTANCES_FROM_TROLLEY",
    UPDATE_TROLLEY_TOTAL: "UPDATE_TROLLEY_TOTAL",
    SHOW_MODAL: "SHOW_MODAL",
    HIDE_MODAL: "HIDE_MODAL"
}

export default actionTypes;